# CircleCI automatically reads this file from our repo and uses it for
# configuration. Docs:
# https://circleci.com/docs/2.0/configuration-reference/
# https://circleci.com/docs/2.0/sample-config/
version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.9

    steps:
      - checkout

      - restore_cache:
          keys:
            - venv-1-{{ .Branch }}

      - run:
          name: Python dependencies
          command: |
            pip install -U pip
            pip -V
            pip install -U .[tests] 'typing-extensions<4.6.0'
            pip install coverage coveralls

      - run:
          name: Python tests
          command: |
            python -m coverage run --source=. --omit=test_\* -m unittest discover -v
            python -m coverage html -d /tmp/coverage_html
            if [ "$COVERALLS_REPO_TOKEN" != "" ]; then python -m coveralls || true; fi

      - save_cache:
          key: venv-1-{{ .Branch }}
          paths:
            - /home/circleci/.pyenv

      - store_artifacts:
          path: /tmp/coverage_html
